{{- if and .Values.runner.namespace (ne .Values.runner.namespace .Release.Namespace) (not (default (dict) .Values.runner).existingSecret) (not .Values.s3.existingSecret) (or .Values.s3.accessKeyId .Values.s3.secretAccessKey) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vuhive-cloud.fullname" . }}-runner-s3
  namespace: {{ .Values.runner.namespace }}
  labels:
    {{- include "vuhive-cloud.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ (default (dict) .Values.runner).existingSecretAccessKey | default .Values.s3.existingSecretAccessKey | default "AWS_ACCESS_KEY_ID" }}: {{ .Values.s3.accessKeyId | quote }}
  {{ (default (dict) .Values.runner).existingSecretSecretKey | default .Values.s3.existingSecretSecretKey | default "AWS_SECRET_ACCESS_KEY" }}: {{ .Values.s3.secretAccessKey | quote }}
{{- end }}
