{{- if or (not .Values.database.existingSecret) (not .Values.s3.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vuhive-cloud.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vuhive-cloud.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if not .Values.database.existingSecret }}
  DATABASE_URL: {{ include "vuhive-cloud.databaseUrl" . | quote }}
  {{- end }}
  {{- if not .Values.s3.existingSecret }}
  AWS_ACCESS_KEY_ID: {{ .Values.s3.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3.secretAccessKey | quote }}
  {{- end }}
{{- end }}
